### PR TITLE
Add TypeScript declaration (index.d.ts)

### PR DESCRIPTION
**Pull request by nkantar**
Not sure if this is something the project wants, but we needed it, so here it is. 😁

### CODE REVIEW

**Comment by arthurkarganyan** [comment]
@nkantar Could you please merge it? I also need typings

**Comment by nkantar** [comment]
@arthurkarganyan I'm not a maintainer for this project.

**Comment by arthurkarganyan** [comment]
@nkantar, sorry ))) 
@bengourley , Could you please help us by merging the code?

**Comment by namenyi** [comment]
@nkantar thanks for the contribution!

This has just been resolved in another PR: https://github.com/bengourley/currency-symbol-map/pull/53

Will publish it soon.

---

cc @arthurkarganyan

**Pull request closed without merging**
