### PR TITLE
Allow for lowercase currency codes

### PR DESCRIPTION
**Pull request by phoenixbox**
#### What's this PR do?
* Allows for lowercase currency codes to be passed
* Fixes backwards test names
* Adds a watch test task

#### Where should the reviewer start?
* `./test.js`

### CODE REVIEW

**Comment by bengourley** [comment]
Great contribution, thanks!

Just one thing, previously the only check that was done with the input was: `currencySymbolMap.hasOwnProperty(currencyCode)`. This meant that falsey/non-string values would never get past this point.

Now though, doing a string operation on it (`.toUpperCase()`) will throw if there's non-string input. This would be a breaking api change but I'd rather handle the bad input and return `undefined` as it currently does.

Can you please fix this and add a test for `undefined` and `null` input?

**Comment by phoenixbox** [comment]
@bengourley sure thing! updated 🌈

**Comment by bengourley** [comment]
Tweaked this a little and published `v3.1.0`. Thanks  🎉

**Comment by phoenixbox** [comment]
@bengourley cool cool 👌 team work dream work

**Pull request merged**
