### PR TITLE
include bower.json

### PR DESCRIPTION
**Pull request by k-funk**

### CODE REVIEW

**Comment by k-funk** [comment]
when it gets merged, i'll add it to the bower registry

**Comment by bestan** [comment]
👍

**Comment by bengourley** [comment]
Thanks for this :smile:

**Comment by k-funk** [comment]
Great! It's now available via `bower install currency-symbol-map`. The registry will auto-updated whenever a semver (ie: `v3.0.1`) tag is pushed to this repo.

**Pull request merged**
