### PR TITLE
Fix Romanian leu symbol

### PR DESCRIPTION
**Pull request by krzychukula**
According to Wikipedia please use sign: L; https://en.wikipedia.org/wiki/Romanian_leu

### CODE REVIEW

**Comment by krzychukula** [comment]
@bengourley Any chance you can take a look?

**Comment by namenyi** [comment]
@krzychukula I've found confusing information, some sites say the symbol is `lei`, while others say it's `L`. The ISO 4217 standard doesn't specify it unfortunately.

Can you please look for an official source that would clearly state which symbol should be used?

I lean towards approving your change, as `L` seems to be more common, but additional information / opinions would be useful.

---

Some sources I checked:

- https://currencyname.com/romania/
- https://en.wikipedia.org/wiki/Romanian_leu
- https://www.xe.com/currency/ron-romanian-leu/
- https://www.investopedia.com/terms/forex/r/ron-romanian-new-leu.asp
- https://transferwise.com/gb/currency-converter/currencies/ron-romanian-leu
- https://www1.oanda.com/currency/iso-currency-codes/RON
- https://eurochange.es/en/exchange-rates/romanian-leu

**Comment by krzychukula** [comment]
I’m far from the expert, but it’s a result of the feedback we got. I have no idea how context-specific it is, but for what it’s worth, we’ve set up a local override for it. 
It also means that if you want to take some time to gather more feedback, then it’s entirely fair to do so :)

**Comment by ilpet** [comment]
@krzychukula @namenyi depends on what you use case is. I can definitely say no-one practically uses L.

Before the revaluation of cutting the 0's in 2005 (see [here](https://en.wikipedia.org/wiki/Romanian_leu#Fourth_leu_.28RON.29:_2005.E2.80.93present)) everyone was using ROL and lei.

After the revaluation people started using RON everywhere to make the distinction (as both old and new prices were shown to get people accustomed). Basically you have old price: 10.000 leu or 10.000 ROL / new price 1 RON.

It kind of stuck as a symbol as well. So if in Hungary you have HUF => Ft., in Poland you have PLN => zł, in Romania you basically have RON => RON. Sometimes, but rarely they still use leu.

And it is always written after the sum, separated by a space, such as 100 RON or 100 leu.

Again this is not official (I do not know of any official sources), but how people practically use it.

**Comment by namenyi** [comment]
@ilpet thanks for the insights! Really useful.

I've just asked another friend who is from Romania, and he said he'd make it `Lei`, but `lei` and `RON` are also widely used and okay. 

He also checked some Romanian invoices he got recently, and they wrote `Lei` and `lei` on them.

---

My conclusion is that we should NOT merge this PR and NOT change it to `L`.

We could change it either to `RON` or `Lei`, probably they would be better options, BUT imho it's not worth the breaking change. 

I would only make such a change if the current version were clearly wrong, which is not the case here.

@krzychukula I'm closing this PR for now.

**Pull request closed without merging**
