### PR TITLE
Add TypeScript typings

### PR DESCRIPTION
**Pull request by LinusU**
Been using these typings in a commercial project for some years now, haven't had any problems with them 👍

### CODE REVIEW

**Comment by LinusU** [comment]
ping @bengourley ☺️

**Comment by sirajalam049** [comment]
Seems like the package is no longer maintained.

**Comment by LinusU** [comment]
@bengourley I'd be happy to jump on as a maintainer if you no longer have time with this :)

**Comment by sirajalam049** [comment]
I created my own package for this, fixes all the issues in this package + typescript + few utils functions too.

https://github.com/sirajalam049/currency-code-symbol-map

**Comment by namenyi** [comment]
@LinusU thanks for the contribution! 

I added a minor change, because there was a warning:

```
Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.
```

Merging it now and will publish it soon.

**Comment by namenyi** [comment]
Released in [v5.0.0](https://github.com/bengourley/currency-symbol-map/releases/tag/v5.0.0)

**Pull request merged**
